<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Dados de reserva</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="shortcut icon" href="favicon.ico">

<!-- Core CSS -->
<link href="<?php echo PASTASISTEMA?>css/b336/css/bootstrap.min.css" rel="stylesheet">
<link href="<?php echo PASTASISTEMA?>css/b336/css/font-awesome.min.css" rel="stylesheet">
<link href="<?php echo PASTASISTEMA?>css/b336/css/personalize.css" rel="stylesheet">

<!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
<!--[if lt IE 9]>
  <script src="<?php echo PASTASISTEMA?>js/html5shiv.js"></script>
  <script src="<?php echo PASTASISTEMA?>js/respond.min.js"></script>
<![endif]--></head><body><section class="entrar content-block">    <div class="container">        <div class="row">			<h2>Dados de reserva</h2>
    		<div class='col-xs-12 text-right'>            	<a href="<?php echo PASTASISTEMA?>Conta/reservas" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-chevron-left" style="font-size:16px"></span> <font style="font-size:14px">Voltar</font></a>            </div>            <?php            if($upd==true):            	$metodo = "Update_Reserva";            else:    	        $metodo = "Insert_Reserva";            endif;            if(($upd==true)&&($update==true)):				echo "<div class='col-xs-12'><h3 style='text-align:center;color:#090''>Reserva alterada com sucesso</h3></div>";			else:				if(($upd==false)&&($update==true)):					echo "<div class='col-xs-12'><h3 style='text-align:center;color:#090'>Reserva feita com sucesso</h3></div>";				endif;			endif;            echo form_open("",array('id'=>'frmItem'));            ?>            <div class="row">                <?php                 $strSala = "";                foreach ($Salas as $Sala):                ?>		                <div class="col-xs-4">							<h5><?php echo $Sala->Sala?></h5>
		                </div>						<div class="col-xs-8">							<h5>Horarios</h5>							<?php 			                foreach ($Horarios as $Horario):			                	$disable = "";			                	$reservado = "";			                	$checado = "";			                	$function = "onclick='reservaSala(".$Sala->ID.",".$Horario->ID.")'";			                	$alt = "alt='0'";			                	foreach ($Reservas as $Reserva):			                		if(($Reserva->IDHora == $Horario->ID)&&($Reserva->IDUSuario != $IDUser)&&($Sala->ID == $Reserva->IDSala)):			                			$disable = "disabled='disabled'";			                			$reservado = "Reservado";			                			$alt = "alt='1'";			                			$function = "";			                			$checado = "";			                		elseif (($Reserva->IDHora == $Horario->ID)&&($Reserva->IDUSuario == $IDUser)):			                			$disable = "disabled='disabled'";			                			$reservado = "Você já reservou.";			                			$checado = "";			                			$function = "";			                		endif;			                	endforeach;			                ?>								<div class="col-xs-4">									<input style="cursor:pointer;" type="checkbox" name="Horario_<?php echo $Sala->ID?>" id="Horario_<?php echo $Sala->ID?>" value="<?php echo $Horario->ID?>" <?php echo$checado." ".$disable." ".$function." ".$alt?> > <?php echo $Horario->Hora." ".$reservado?> 								</div>							<?php 					       	endforeach;					       	?>				                </div>		            <div class="col-xs-12"><hr></div>  		       <?php 		       		$strSala .= $Sala->ID.",";		       endforeach;		       ?>                     <div class="row">                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">                    <div class="form-group">                        <input type="submit" name="submit" id="submit" value="Salvar reserva" class="btn btn-primary">&nbsp;<a href="<?php echo PASTASISTEMA?>Conta/reservas" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-remove-sign" style="font-size:20px"></span> <font style="font-size:16px">Cancelar</font></a>                    </div>                </div>            </div>			<input type="hidden" name="Salas" id="Salas" value="<?php echo $strSala?>">
        <?php        echo form_close();        ?>        </div>    </div></section>
<script type="text/javascript" src="<?php echo PASTASISTEMA?>js/jquery-1.11.1.min.js"></script>			<script type="text/javascript" src="<?php echo PASTASISTEMA?>js/bootstrap.min.js"></script>
<script type="text/javascript">function reservaSala(sala,hora){	var strSala = $("#Salas").val().split(",");	var qtdSala = (strSala.length - 1);	for(s=0;s<=qtdSala;s++){		$('input:checkbox[name=Horario_'+strSala[s]+']').each(function() {			if(($(this).val()==hora)&&(strSala[s]!=sala)){				if($(this).attr("disabled")){					if($(this).attr("alt")!=1){						$(this).attr("disabled",false);					}					}else{						if($(this).attr("alt")!=1){						$(this).attr("disabled",true);					}				}				};		});	}	}$(document).ready(function(){	$("#frmItem").submit(function(event){		var strSala = $("#Salas").val().split(",");		var qtdSala = (strSala.length - 1);		var arrSala = "";		var arrValor = "";				alert(qtdSala);		for(s=0;s<=qtdSala-1;s++){			arrSala += strSala[s]+",";			var arrS = "";						$('input:checkbox[name=Horario_'+strSala[s]+']').each(function() {				if ($(this).is(':checked')){					arrS += $(this).val()+"-";				}							});			arrValor += arrS+",";		}		if(arrValor!=""){						$.ajax({				type: "POST", 				dataType: "json",				url: "<?php echo PASTASISTEMA?>Conta/Insert_reservas", 				data: "reservas="+arrValor+"&salas="+arrSala, 				success: function(data){					if(data.sucesse==true){						location.href = "<?php echo PASTASISTEMA?>Conta/reservas";					}				}			});		}else{			alert("Selecione a(s) sala(s) e horario para reserva");					}					return false;	});})</script></body></html>